#!/usr/bin/env python3
"""
Borg Backup Runner — runs `borg create` for a set of paths against a repository
(on another machine over SSH, or local), then prunes, optionally compacts and
verifies, and prints a report saying what was backed up, where, how long it
took, and whether the whole run succeeded.

Modelled on the scripts generated by the openmediavault borgbackup plugin, so a
job can be moved here without changing behaviour:

  * `borg create --verbose --filter AME --list --stats --show-rc
     --compression auto,lzma,9 --exclude-caches ::<prefix>-<timestamp>`
  * `borg prune --list --glob-archives '<prefix>-*' --keep-weekly 4 --keep-monthly 3`
  * `borg compact --verbose --threshold 10`
  * `BORG_EXIT_CODES=modern`, `BORG_LOCK_WAIT` default 3600
  * one flock per repository so two runs never fight over the repository lock
  * exit-code classes identical to the plugin: 0 ok, 1 warning, 2..99 error,
    100..127 warning, >=128 killed by a signal. The worst phase decides the
    overall status, which becomes this script's exit status (0 ok, 1 warnings,
    2 failure, 4 repository busy).
  * `--init` runs `borg init` / `borg2 repo-create` when borg reports that the
    repository does not exist — borg >= 1.2 refuses to create one by itself,
    and the plugin generates an `init` step for the same reason.

The passphrase only ever reaches borg through the environment
(BORG_PASSPHRASE / BORG_PASSCOMMAND) and is redacted everywhere else.

Requirements: `borg` 1.x (the borg 2 command line is detected and adapted),
source paths readable by the running user, SSH key access for user@host:/path
repositories.
"""

import argparse
import errno
import fcntl
import getpass
import hashlib
import os
import re
import shlex
import shutil
import signal as signal_module
import subprocess
import sys
import time

# ---------------------------------------------------------------------------
# Terminal formatting (self-contained copy of the helpers used by the smart/
# scripts so that every script stays standalone)
# ---------------------------------------------------------------------------

ANSI_ESCAPE = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")


class Colors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"


USE_COLOR = sys.stdout.isatty()


def configure_color(force=None):
    """
    Resolve whether ANSI color codes are emitted.

    By default colors follow tty detection (stdout piped/redirected -> plain).
    `force=True` overrides that and emits colors anyway (used by --color);
    `force=False` suppresses them; `force=None` leaves the detected value
    untouched. Returns the resulting setting.
    """
    global USE_COLOR
    if force is not None:
        USE_COLOR = bool(force)
    return USE_COLOR


def colorize(text, color_code):
    if USE_COLOR:
        return f"{color_code}{text}{Colors.ENDC}"
    return text


def visible_len(text):
    return len(ANSI_ESCAPE.sub("", str(text)))


def fit(text, width):
    text = str(text)
    if visible_len(text) <= width:
        return text
    out = []
    used = 0
    i = 0
    while i < len(text):
        if text.startswith("\x1b", i):
            match = ANSI_ESCAPE.match(text, i)
            if match:
                out.append(match.group(0))
                i = match.end()
                continue
        if used >= width - 1:
            break
        out.append(text[i])
        used += 1
        i += 1
    out.append("…")
    if ANSI_ESCAPE.search("".join(out)):
        out.append(Colors.ENDC)
    return "".join(out)


def print_table(headers, rows, max_widths=None):
    widths = [len(h) for h in headers]
    for row in rows:
        for i, value in enumerate(row):
            widths[i] = max(widths[i], visible_len(value))
    if max_widths:
        widths = [min(w, m) for w, m in zip(widths, max_widths)]

    print("│".join(fit(h, w).center(w) for h, w in zip(headers, widths)))
    print("├".join("─" * w for w in widths))
    for row in rows:
        cells = []
        for i, value in enumerate(row):
            pad = max(0, widths[i] - visible_len(value))
            cells.append(fit(value, widths[i]) + " " * pad)
        print("│".join(cells))


def human_bytes(value):
    if value is None:
        return "-"
    value = float(value)
    if value < 1000:
        return f"{value:.0f} B"
    units = ["kB", "MB", "GB", "TB", "PB", "EB"]
    n = -1
    while value >= 1000 and n < len(units) - 1:
        value /= 1000.0
        n += 1
    return f"{value:.2f} {units[n]}"


def human_duration(seconds):
    if seconds is None:
        return "-"
    seconds = int(seconds)
    hours, rest = divmod(seconds, 3600)
    minutes, secs = divmod(rest, 60)
    if hours:
        return f"{hours}h{minutes:02d}m{secs:02d}s"
    if minutes:
        return f"{minutes}m{secs:02d}s"
    return f"{secs}s"


def stamp():
    return time.strftime("%H:%M:%S")


def log_line(text, stream=sys.stdout):
    print(f"[{stamp()}] {text}", file=stream, flush=True)


def fail(message, code=2):
    print(colorize(f"Error: {message}", Colors.FAIL + Colors.BOLD),
          file=sys.stderr)
    sys.exit(code)


# ---------------------------------------------------------------------------
# Which borg to run, and what that version understands
# ---------------------------------------------------------------------------

# Debian coinstalls borgbackup (/usr/bin/borg, 1.x) and borgbackup2
# (/usr/bin/borg2, 2.x), so the binary is an option: --borg.
BORG_BIN = "borg"


def borg_version():
    res = subprocess.run([BORG_BIN, "--version"], capture_output=True, text=True)
    if res.returncode != 0:
        return "", 0
    match = re.search(r"(\d+)\.(\d+)", res.stdout or "")
    if not match:
        return (res.stdout or "").strip(), 0
    return match.group(0), int(match.group(1))


_HELP_CACHE = {}


def help_text(verb):
    if verb not in _HELP_CACHE:
        res = subprocess.run([BORG_BIN, verb, "--help"],
                             capture_output=True, text=True)
        _HELP_CACHE[verb] = (res.stdout or "") + (res.stderr or "")
    return _HELP_CACHE[verb]


def supports(verb, flag):
    """Whether this borg build knows FLAG for the given verb."""
    return re.search(re.escape(flag) + r"(?![\w-])", help_text(verb)) is not None


# ---------------------------------------------------------------------------
# Borg exit codes with BORG_EXIT_CODES=modern
# (table taken from borg's own sources: constants.py EXIT_*, plus every
#  exit_mcode in helpers/errors.py, key.py, repository.py, locking.py,
#  remote.py, cache.py, archive.py, manifest.py, parseformat.py)
# ---------------------------------------------------------------------------

RC_GENERIC = {0: "success", 1: "warning", 2: "error"}

RC_MEANING = {
    3: "cancelled by user",
    4: "command line error",
    5: "archive-name format error",
    6: "invalid placeholder in archive name",
    10: "a repository already exists there",
    11: "attic repository, run 'borg upgrade'",
    12: "repository inconsistency, run 'borg check'",
    13: "repository does not exist",
    14: "insufficient free space in the repository",
    15: "not a valid repository",
    16: "invalid repository configuration",
    17: "object not found in repository",
    18: "parent path of the repository does not exist",
    19: "repository path already exists",
    20: "repository storage quota exceeded",
    21: "permission denied for the repository path",
    25: "repository needs a newer borg (features)",
    26: "repository has no manifest",
    27: "unsupported manifest, newer borg required",
    30: "archive already exists",
    31: "archive does not exist",
    32: "filesystem encoding problem (check LANG)",
    40: "invalid key data for the repository",
    41: "key file does not match the repository",
    42: "key file not found for the repository",
    43: "not a borg key backup",
    44: "no key entry in the repository config",
    45: "key backup belongs to another repository",
    46: "unencrypted repository has no key management",
    47: "unknown key type",
    48: "payload needs a newer borg",
    50: "cannot acquire a passphrase",
    51: "BORG_PASSCOMMAND failed",
    52: "passphrase incorrect",
    53: "too many passphrase retries",
    60: "cache initialization aborted",
    61: "repository encryption method changed",
    62: "repository access aborted",
    63: "cache newer than repository (two repos, same id?)",
    64: "cache/security data newer than repository",
    70: "failed to acquire the lock",
    71: "failed to acquire the lock (fatal)",
    72: "failed to create/acquire the lock",
    73: "lock timeout — another borg is using the repository",
    74: "lock was not held",
    75: "lock held by somebody else",
    80: "connection closed by the remote host",
    81: "connection closed by the remote host (see message)",
    82: "invalid RPC method",
    83: "repository path not allowed by 'borg serve'",
    84: "borg server on the other side is too old",
    85: "unexpected RPC data format from client",
    86: "unexpected RPC data format from server",
    87: "connection to the remote host is broken",
    90: "data integrity error",
    91: "file failed its integrity check",
    92: "decompression error",
    95: "archive authentication did not verify",
    96: "archive authentication required",
    97: "manifest authentication did not verify",
    98: "manifest authentication required",
    99: "TAM authentication failure",
    100: "a file changed while being backed up",
    101: "an include pattern never matched",
    102: "backup error on one file",
    103: "file type/inode changed during backup (race)",
    104: "backup OSError on one file",
    105: "permission denied while backing up a file",
    106: "I/O error while backing up a file",
    107: "file disappeared while backing it up",
}


def rc_class(rc):
    if rc == 0:
        return "ok"
    if rc == 1:
        return "warn"
    if 2 <= rc <= 99:
        return "err"
    if 100 <= rc <= 127:
        return "warn"
    if rc >= 128:
        return "sig"
    return "err"


def signal_name(rc):
    try:
        return signal_module.Signals(rc - 128).name
    except (ValueError, OSError):
        return f"signal {rc - 128}"


def rc_label(rc):
    cls = rc_class(rc)
    if cls == "ok":
        return "ok"
    if cls == "sig":
        return f"killed: {signal_name(rc)}"
    kind = "warning" if cls == "warn" else "error"
    meaning = RC_MEANING.get(rc) or RC_GENERIC.get(rc)
    if meaning:
        return f"{kind}({rc}: {meaning})"
    return f"{kind}({rc})"


STATUS_COLOR = {"ok": Colors.OKGREEN, "warn": Colors.WARNING,
                "err": Colors.FAIL, "sig": Colors.FAIL}


# ---------------------------------------------------------------------------
# Parsing borg's statistics block
# ---------------------------------------------------------------------------

SIZE_UNITS = {"B": 1, "KB": 1000, "MB": 1000 ** 2, "GB": 1000 ** 3,
              "TB": 1000 ** 4, "PB": 1000 ** 5,
              "KIB": 1024, "MIB": 1024 ** 2, "GIB": 1024 ** 3,
              "TIB": 1024 ** 4, "PIB": 1024 ** 5}


def parse_size(text):
    """'22.88 GB' -> bytes, matching borg's 1000-based unit reporting."""
    text = (text or "").strip()
    match = re.match(r"^([\d.,]+)\s*([A-Za-z]*)(?:i?B)?$", text)
    if not match:
        return None
    value = float(match.group(1).replace(",", ""))
    unit = (match.group(2) or "B").upper()
    if unit == "":
        unit = "B"
    if unit not in SIZE_UNITS:
        return None
    return value * SIZE_UNITS[unit]


SIZES_RE = re.compile(r"([\d.,]+)\s*([A-Za-z]{1,2}B?)")


def split_sizes(text):
    """'3.20 MB 3.00 MB 3.00 MB' -> ['3.20 MB', '3.00 MB', '3.00 MB']."""
    pairs = SIZES_RE.findall(text or "")
    return [f"{value} {unit.strip()}" for value, unit in pairs[:3]]


def parse_duration(text):
    """'8 minutes 40.52 seconds' -> 520.52; also accepts 'H:MM:SS.aa'."""
    text = (text or "").strip()
    if not text:
        return None
    multipliers = {"day": 86400, "hour": 3600, "minute": 60, "second": 1}
    total = 0.0
    found = False
    for value, unit in re.findall(r"([\d.]+)\s*(days?|hours?|minutes?|seconds?)",
                                  text, re.I):
        total += float(value) * multipliers[unit.lower().rstrip("s")]
        found = True
    if found:
        return total
    parts = text.split(":")
    if len(parts) == 3:
        try:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
        except ValueError:
            return None
    return None


# borg --list prints one status character per item ("A /path", "U /path", …)
ITEM_LINE = re.compile(r"^[A-Za-z><]\s")

# borg 1.x writes progress chatter, the --list items, the statistics block and
# the actual problem to the *same* stream. Everything matching this is not
# interesting in the report; what is left over becomes a message when a phase
# fails. Patterns are from observed `borg create/prune/compact/check --verbose`
# output (borg 1.4) plus argparse's usage dump.
_BORING = [
    r"^\s",                       # indented: traceback or argparse continuation
    r"^[A-Za-z><]\s",              # --list item line
    r"^-{5,}$",                    # statistics block separator
    r"^\[?-{1,2}\w",               # argparse option dump: "[-h]", "--stats SPEC"
    r"^usage:",                    # argparse usage banner
    r"\[PATH ",                    # argparse parameter line
    r"^(Original size|Unique chunks)\s\s",  # statistics column headers (1.x)
    r"^(Original|Compressed|Deduplicated) size$",
    r"^Creating (archive at|repository)",
    r"^Initializing repository",
    r"^Synchronizing chunks cache",
    r"^Archives: \d+, ",
    r"^(Fetching and building|Reading cached) archive",
    r"^Merging into master chunks index",
    r"^Building master chunks index",
    r"^Done\.?$",
    r"^Determining archives to clean up",
    r"^(Keeping|Pruning) archive",
    r"^Would (remove|prune) ",
    r"^Would have been removed",
    r"^Starting archive consistency check",
    r"^(Analyzing|Verifying) ",
    r"^Orphaned objects check skipped",
    r"^Archive consistency check complete",
    r"^Remote: Warning: Permanently added",          # ssh host-key chatter
    r"^(Added|Unchanged|Modified|Error) files:",      # borg 2 stats fields
    r"^Files changed while reading:",
    r"^Bytes (read from|sent to) remote:",
    r"^Time spent in \w+:",
    r"^compaction freed",
    r"^check_free_space",
    r"^Using security path",
    r"^using service cmdline",
    r"^Lock: ",
    r"^(Waiting on|Acquired) lock",
    r"^Trying to create exclusive lock",
    r"^Detaching after fork",
    r"^Initializing cache transaction",
    r"^Saving (files|chunks) cache",
    r"^Saving cache config",
    r"^Generating a new key",
    r"^storing key for repo id",
    r"^Security directory",
    r"^(Platform|Linux|Borg|PID|sys\.argv|SSH_ORIGINAL_COMMAND):",
]
BORING = re.compile("|".join(f"(?:{pattern})" for pattern in _BORING))


class Stats:
    """Everything interesting from one borg phase's output."""

    FIELDS = (
        ("repository", r"^Repository:\s+(.+)$"),
        ("archive", r"^Archive name:\s+(.+)$"),
        ("fingerprint", r"^Archive (?:fingerprint|id):\s+(.+)$"),
        ("start", r"^Time \(start\):\s+(.+)$"),
        ("end", r"^Time \(end\):\s+(.+)$"),
        ("duration_text", r"^Duration:\s+(.+)$"),
        ("files", r"^Number of files:\s+([\d,.]+)$"),
        ("utilization", r"^Utilization of max\. archive size:\s+(\d+)"),
        ("chunk_index", r"^Chunk index:\s+([\d,.]+)\s+([\d,.]+)$"),
        ("this_archive", r"^(?:This archive|Archive):\s+(.+)$"),
        ("all_archives", r"^All archives:\s+(.+)$"),
        # borg 2 has no size triple; it reports these flat fields instead
        ("original", r"^Original size:\s+(.+)$"),
        ("compressed", r"^Compressed size:\s+(.+)$"),
        ("deduplicated", r"^Deduplicated size:\s+(.+)$"),
    )

    def __init__(self):
        self.repository = None
        self.archive = None
        self.fingerprint = None
        self.start = None
        self.end = None
        self.duration_text = None
        self.files = None
        self.utilization = None
        self.chunk_index = None
        self.this_archive = None
        self.all_archives = None
        self.original = self.compressed = self.deduplicated = None
        self.warnings = []
        self.errors = []
        # lines that matched nothing (become messages when the phase failed)
        self.plain = []

    def feed(self, raw_line):
        line = raw_line.strip()
        if not line:
            return
        for name, pattern in self.FIELDS:
            match = re.search(pattern, line)
            if not match:
                continue
            if name == "chunk_index":
                self.chunk_index = tuple(match.groups())
            elif name in ("this_archive", "all_archives"):
                setattr(self, name, split_sizes(match.group(1)))
            else:
                setattr(self, name, match.group(1))
            return

        if re.match(r"^(Warning|WARNING):", line):
            self.warnings.append(re.sub(r"^(Warning|WARNING):\s*", "", line))
        elif re.match(r"^(ERROR|Error):", line):
            self.errors.append(re.sub(r"^(ERROR|Error):\s*", "", line))
        elif line.startswith(("Command Error:", "Local Exception",
                              "borg: error:", "Traceback (most recent call")):
            self.errors.append(line)
        elif not BORING.match(raw_line):
            # borg mixes progress chatter, usage dumps and the real problem on
            # the same stream; keep the lines that are neither, in case the
            # phase ends up failing (see phase_messages).
            self.plain.append(line)

    def size(self, which, index):
        triple = getattr(self, which)
        if not triple or index >= len(triple):
            return None
        return parse_size(triple[index])

    def dedup_bytes(self):
        """New data in this archive; both borg stats layouts are read."""
        value = self.size("this_archive", 2)
        if value is None and self.deduplicated:
            value = parse_size(self.deduplicated)
        return value

    def sizes_summary(self):
        """The size line, from borg 1.x's triple or borg 2's flat fields."""
        if self.this_archive:
            names = ("original", "compressed", "deduplicated")
            return "  ".join(f"{name} {value}"
                             for name, value in zip(names, self.this_archive))
        pairs = (("original", self.original), ("compressed", self.compressed),
                 ("deduplicated", self.deduplicated))
        return "  ".join(f"{name} {value}"
                         for name, value in pairs if value) or "-"

    @property
    def duration(self):
        return parse_duration(self.duration_text)

    @property
    def complete(self):
        return bool(self.archive or self.files or self.this_archive
                    or self.deduplicated)


# ---------------------------------------------------------------------------
# Phase runner
# ---------------------------------------------------------------------------

def redact(text):
    """Never let a passphrase reach the terminal, the log, or an exception."""
    text = re.sub(r"(BORG_PASSPHRASE=)\S+", r"\1<redacted>", text)
    return re.sub(r"(--passphrase[ =])\S+", r"\1<redacted>", text)


class Runner:
    """Runs borg phases, streams their output, and records everything."""

    def __init__(self, env, log_file, quiet):
        self.env = env
        self.log_file = log_file
        self.quiet = quiet
        self.phases = []
        self._log = None
        if log_file:
            try:
                self._log = open(log_file, "a", encoding="utf-8")
            except OSError as exc:
                log_line(f"Warning: cannot append to {log_file}: {exc}",
                         stream=sys.stderr)

    def write_log(self, text):
        if self._log:
            try:
                self._log.write(text)
                self._log.flush()
            except OSError as exc:
                log_line(f"Warning: log file write failed ({exc}); continuing "
                         f"without a log.", stream=sys.stderr)
                try:
                    self._log.close()
                except OSError:
                    pass
                self._log = None

    def close(self):
        if self._log:
            try:
                self._log.close()
            except OSError:
                pass
            self._log = None

    def run(self, name, argv):
        printable = redact(" ".join(shlex.quote(a) for a in argv))
        log_line(f"{name}: {printable}")
        self.write_log(f"\n{time.strftime('%F %T')} {name}: {printable}\n")

        started = time.monotonic()
        process = subprocess.Popen(
            argv, env=self.env, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, text=True, errors="replace", bufsize=1,
        )

        stats = Stats()
        counters = {"added": 0, "changed": 0}
        for raw in process.stdout:
            line = raw.rstrip("\n").rstrip("\r")
            stats.feed(line)
            self.write_log(line + "\n")
            if not self.quiet:
                print(line, flush=True)
            # borg item lines: A = archived (new), M = modified
            if ITEM_LINE.match(line) and line[0] in "AM":
                counters["added" if line[0] == "A" else "changed"] += 1

        rc = process.wait()
        elapsed = time.monotonic() - started
        cls = rc_class(rc)
        log_line(f"{name} finished in {human_duration(elapsed)}: "
                 f"{colorize(rc_label(rc), STATUS_COLOR[cls])}")
        self.write_log(f"{name}: rc={rc} ({cls}) in {elapsed:.2f}s\n")
        self.phases.append({
            "name": name, "rc": rc, "class": cls, "elapsed": elapsed,
            "stats": stats, "argv": printable, "counters": counters,
        })
        return self.phases[-1]


# ---------------------------------------------------------------------------
# Repository lock (one lock per repository, like the OMV plugin)
# ---------------------------------------------------------------------------

def acquire_lock(repo, wait, enabled):
    """Returns a lock handle, None when disabled, or 'timeout'."""
    if not enabled:
        return None
    repo_id = hashlib.sha256(repo.encode()).hexdigest()[:16]
    for directory in ("/run/lock", "/var/tmp", "/tmp"):
        try:
            os.makedirs(directory, exist_ok=True)
            path = os.path.join(directory, f"borg-backup-{repo_id}.lock")
            handle = open(path, "w")
        except OSError:
            continue
        deadline = time.monotonic() + max(0, wait)
        log_line(f"Waiting for repo lock ({wait}s): {path}")
        while True:
            try:
                fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
                log_line(f"Acquired repo lock: {path}")
                return handle
            except OSError as exc:
                if exc.errno not in (errno.EACCES, errno.EAGAIN):
                    handle.close()
                    raise
                if time.monotonic() >= deadline:
                    handle.close()
                    log_line(f"Failed to acquire repo lock after {wait}s: {path}",
                             stream=sys.stderr)
                    return "timeout"
                time.sleep(1)
    log_line("Warning: no writable lock directory; running without a lock.",
             stream=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# Passphrase resolution
# ---------------------------------------------------------------------------

def resolve_passphrase(args):
    """
    Return (description, env_updates). The secret itself only goes into `env`.

    Precedence: --password, --password-file, $<--password-env>,
    --password-command, $BORG_PASSCOMMAND, interactive prompt.
    """
    if args.password is not None:
        return ("--password on the command line (visible in `ps`; prefer "
                "--password-file)", {"BORG_PASSPHRASE": args.password})

    if args.password_file:
        try:
            with open(args.password_file, encoding="utf-8") as handle:
                secret = handle.readline().rstrip("\r\n")
        except OSError as exc:
            fail(f"cannot read password file {args.password_file}: {exc}")
        return (f"--password-file {args.password_file}",
                {"BORG_PASSPHRASE": secret})

    if args.password_env in os.environ:
        return (f"environment ${args.password_env}",
                {"BORG_PASSPHRASE": os.environ[args.password_env]})

    if args.password_command:
        return (f"--password-command {args.password_command}",
                {"BORG_PASSCOMMAND": args.password_command})

    if "BORG_PASSCOMMAND" in os.environ:
        return ("environment $BORG_PASSCOMMAND", {})

    if sys.stdin.isatty():
        return ("interactive prompt",
                {"BORG_PASSPHRASE": getpass.getpass(
                    "Repository passphrase (empty if the repo has none): ")})

    return ("none provided — borg will prompt on the terminal or fail", {})


# ---------------------------------------------------------------------------
# Command construction
# ---------------------------------------------------------------------------

KEEP_OPTIONS = ("keep-within", "keep-last", "keep-secondly", "keep-minutely",
                "keep-hourly", "keep-daily", "keep-weekly", "keep-monthly",
                "keep-yearly")

# The openmediavault borgbackup job this script replaces.
DEFAULT_RETENTION = {"keep-weekly": 4, "keep-monthly": 3}


def resolve_retention(args):
    """Explicit --keep-* wins; otherwise the OMV defaults are used."""
    given = {}
    for option in KEEP_OPTIONS:
        value = getattr(args, option.replace("-", "_"), None)
        if value is not None:
            given[option] = value
    if given:
        return given, False
    return dict(DEFAULT_RETENTION), True


class Borg:
    """Builds borg command lines for the installed borg major version."""

    def __init__(self, major):
        self.major = major
        # Differences that matter here (probed, not assumed): borg 2 takes the
        # archive as a positional instead of repository::archive, spells
        # --glob-archives as --match-archives, and has no compact --threshold.
        self.show_rc = supports("create", "--show-rc")
        self.stats = supports("create", "--stats")
        self.list_flag = "--list" if supports("create", "--list") else None
        if supports("prune", "--glob-archives"):
            self.archives_filter = "--glob-archives"
            self.archives_prefix = ""
        else:
            self.archives_filter = "--match-archives"
            self.archives_prefix = "sh:"

    def archive_glob(self, pattern):
        return self.archives_prefix + pattern

    def init_mode(self, args):
        return args.encryption or ("repokey-blake2-aes-ocb" if self.major >= 2
                                   else "repokey-blake2")

    def init(self, args):
        verb = "repo-create" if self.major >= 2 else "init"
        return [BORG_BIN, verb, "--encryption", self.init_mode(args)]

    def create(self, args, archive, sources):
        cmd = [BORG_BIN, "create", "--verbose"]
        if args.dry_run:
            cmd += ["--dry-run"]
        if args.list_files and self.list_flag:
            cmd += [self.list_flag]
            if args.filter and supports("create", "--filter"):
                cmd += ["--filter", args.filter]
        if self.stats and not args.dry_run:
            # a dry run has nothing to report statistics about
            cmd += ["--stats"]
        if self.show_rc and args.show_rc:
            cmd += ["--show-rc"]
        cmd += ["--compression", args.compression]
        if args.exclude_caches:
            cmd += ["--exclude-caches"]
        for pattern in args.exclude:
            cmd += ["--exclude", pattern]
        for path in args.exclude_from:
            cmd += ["--exclude-from", path]
        if args.create_args:
            cmd += shlex.split(args.create_args)
        # borg 1.x: "repository::archive" (repository comes from BORG_REPO);
        # borg 2: the archive name is the first positional argument.
        cmd.append(archive if self.major >= 2 else "::" + archive)
        return cmd + list(sources)

    def prune(self, args, prefix, retention):
        cmd = [BORG_BIN, "prune"]
        if args.list_files and self.list_flag:
            cmd += [self.list_flag]
        for option in KEEP_OPTIONS:
            if option in retention:
                cmd += [f"--{option}", str(retention[option])]
        if self.show_rc and args.show_rc:
            cmd += ["--show-rc"]
        cmd += [self.archives_filter, self.archive_glob(f"{prefix}-*")]
        if args.dry_run:
            cmd += ["--dry-run"]
        return cmd

    def compact(self, args):
        cmd = [BORG_BIN, "compact", "--verbose"]
        if supports("compact", "--threshold"):
            cmd += ["--threshold", str(args.compact_threshold)]
        return cmd

    def check(self, args, archive):
        cmd = [BORG_BIN, "check", "--verbose"]
        if supports("check", "--archives-only"):
            cmd += ["--archives-only"]
        if supports("check", "--glob-archives"):
            cmd += ["--glob-archives", archive]
        elif supports("check", "--match-archives"):
            cmd += ["--match-archives", "sh:" + archive]
        return cmd

    def list_archives(self, count):
        # borg 2 lists a repository's archives with the repo-list command; its
        # plain "list" needs an archive name and lists that archive's contents.
        cmd = [BORG_BIN, "repo-list" if self.major >= 2 else "list"]
        verb = cmd[1]
        if supports(verb, "--last"):
            cmd += ["--last", str(count)]
        if self.major < 2 and supports(verb, "--short"):
            # borg 2's repo-list --short prints bare ids; its default format
            # (id, timestamp, name, user, host) is what is worth seeing.
            cmd += ["--short"]
        return cmd


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def build_parser():
    epilog = (
        "examples:\n"
        "  # a job on another box, repository over ssh:\n"
        "  borg_backup.py -r borg@backup-server:/srv/pool/borg \\\n"
        "      --password-file /root/.config/borg/vm_images.pw -n vm_images \\\n"
        "      /srv/pool/vms\n\n"
        "  # local repository, tighter retention, only the summary on stdout:\n"
        "  BORG_PASSPHRASE=secret borg_backup.py -r /backup/repo -q \\\n"
        "      --keep-daily 7 --keep-monthly 6 /etc /root\n\n"
        "  # first run: borg will not create a repository, so ask for it:\n"
        "  borg_backup.py -r /backup/repo --init --keep-daily 7 /etc\n\n"
        "  # see what would be archived and pruned, write nothing:\n"
        "  borg_backup.py -r /backup/repo --dry-run /var/log\n"
    )
    p = argparse.ArgumentParser(
        prog="borg_backup.py",
        description="Run a borg backup (create + prune + compact) and report "
                    "what was archived, where, how long it took, and whether "
                    "the run succeeded.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=epilog,
    )
    p.add_argument("sources", nargs="+", metavar="PATH",
                   help="files or directories to back up")

    conn = p.add_argument_group("repository")
    conn.add_argument("-r", "--repo", default=os.environ.get("BORG_REPO"),
                      metavar="REPO",
                      help="borg repository: user@host:/path, "
                           "ssh://user@host/path or a local path "
                           "(default: $BORG_REPO)")
    conn.add_argument("--password", metavar="PASSPHRASE", default=None,
                      help="repository passphrase; visible in `ps`, so prefer "
                           "--password-file or $BORG_PASSPHRASE")
    conn.add_argument("--password-file", metavar="FILE",
                      help="read the passphrase from the first line of FILE")
    conn.add_argument("--password-env", metavar="NAME", default="BORG_PASSPHRASE",
                      help="environment variable holding the passphrase "
                           "(default: %(default)s)")
    conn.add_argument("--password-command", metavar="CMD",
                      help="command that prints the passphrase (BORG_PASSCOMMAND)")
    conn.add_argument("--rsh", default=os.environ.get("BORG_RSH"), metavar="CMD",
                      help="ssh command for remote repositories (BORG_RSH), "
                           "e.g. 'ssh -i /root/.ssh/borg -p 22'")

    arc = p.add_argument_group("archive contents")
    arc.add_argument("-n", "--name", metavar="PREFIX",
                     help="archive prefix; the archive is <PREFIX>-<timestamp> "
                          "(default: hostname)")
    arc.add_argument("--compression", default="auto,lzma,9", metavar="SPEC",
                     help="borg compression specification (default: %(default)s)")
    arc.add_argument("--filter", default="AME", metavar="STATUSCHARS",
                     help="only list items with these borg status characters, "
                           "A=added M=modified E=new attributes; pass '' to "
                           "list unchanged items too (default: %(default)s)")
    arc.add_argument("--no-list", dest="list_files", action="store_false",
                     help="do not list archived items, only print the report")
    arc.add_argument("--exclude", action="append", default=[], metavar="PATTERN",
                     help="exclude a shell pattern (repeatable)")
    arc.add_argument("--exclude-from", action="append", default=[], metavar="FILE",
                     help="read exclude patterns from a file (repeatable)")
    arc.add_argument("--no-exclude-caches", dest="exclude_caches",
                     action="store_false",
                     help="do not skip directories marked with CACHEDIR.TAG")
    arc.add_argument("--create-args", default="", metavar="ARGS",
                     help="extra raw arguments for borg create, e.g. "
                          "--create-args='--one-file-system --numeric-owner'")

    ret = p.add_argument_group(
        "retention",
        "pruning happens after a successful create and only touches archives "
        "named <PREFIX>-*; with no --keep-* options the openmediavault job "
        "defaults (keep-weekly 4, keep-monthly 3) are used")
    for option in KEEP_OPTIONS:
        ret.add_argument("--" + option, dest=option.replace("-", "_"),
                         type=int, metavar="N", default=None,
                         help=f"keep {option[5:]} archives")
    ret.add_argument("--no-prune", action="store_true",
                     help="skip the prune phase entirely")
    ret.add_argument("--no-compact", action="store_true",
                     help="skip the compact phase")
    ret.add_argument("--compact-threshold", type=int, default=10, metavar="PCT",
                     help="compact repositories with less than this percent "
                          "free (default: %(default)s)")

    run = p.add_argument_group("run control")
    run.add_argument("--borg", default="borg", metavar="PATH",
                     help="borg executable to run (default: %(default)s; "
                          "Debian's borgbackup2 package ships it as borg2)")
    run.add_argument("--dry-run", action="store_true",
                     help="create and prune with --dry-run: nothing is written "
                          "(borg also disables --stats, so no size statistics)")
    run.add_argument("--verify", action="store_true",
                     help="afterwards run 'borg check' on the new archive")
    run.add_argument("--init", action="store_true",
                     help="if borg reports that the repository does not exist "
                          "or is not initialized, initialize it and retry "
                          "(borg does that by itself only for a path that does "
                          "not exist yet — an existing empty directory is "
                          "rejected)")
    run.add_argument("--encryption", metavar="MODE",
                     help="encryption mode for --init (default: "
                          "repokey-blake2 on borg 1.x, "
                          "repokey-blake2-aes-ocb on borg 2)")
    run.add_argument("--show-archives", type=int, default=0, metavar="N",
                     help="also list the N newest archives of the repository")
    run.add_argument("--log-file", metavar="FILE",
                     help="append full borg output to FILE "
                          "(default: /var/log/borgbackup/<PREFIX>.log)")
    run.add_argument("--no-log", dest="log", action="store_false",
                     help="do not write a log file")
    run.add_argument("--lock-wait", type=int,
                     default=int(os.environ.get("BORG_LOCK_WAIT", 3600)),
                     metavar="SECONDS",
                     help="how long to wait for this repository's lock "
                          "(default: 3600, $BORG_LOCK_WAIT)")
    run.add_argument("--no-lock", dest="lock", action="store_false",
                     help="do not serialize runs against this repository")
    run.add_argument("--keep-env", action="store_true",
                     help="do not set BORG_EXIT_CODES/BORG_LOCK_WAIT ourselves")
    run.add_argument("--show-rc", action="store_true",
                     help="ask borg to print its own 'exit code: N' line")
    run.add_argument("-q", "--quiet", action="store_true",
                     help="hide borg's own output; print only the report")
    run.add_argument("-c", "--color", action="store_true",
                     help="force ANSI colors even when stdout is not a terminal "
                          "(piped / redirected output)")
    p._optionals.title = "help"
    return p


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = build_parser().parse_args()
    configure_color(True if args.color else None)

    global BORG_BIN
    BORG_BIN = args.borg
    if shutil.which(BORG_BIN) is None:
        fail(f"'{BORG_BIN}' is not installed or not in PATH "
             f"(apt install borgbackup, or borgbackup2 for /usr/bin/borg2)")

    if not args.repo:
        fail("no repository given: pass -r/--repo or set $BORG_REPO")

    missing = [s for s in args.sources if not os.path.exists(s)]
    if missing:
        fail("source path(s) do not exist: " + ", ".join(missing))

    if args.no_prune and any(getattr(args, o.replace("-", "_"), None) is not None
                             for o in KEEP_OPTIONS):
        fail("--no-prune cannot be combined with --keep-* options")

    version, major = borg_version()
    if not major:
        fail("could not determine the borg version")
    borg = Borg(major)
    retention, defaulted = resolve_retention(args)

    repo = args.repo
    prefix = args.name or os.uname().nodename
    archive = f"{prefix}-{time.strftime('%Y-%m-%d_%H-%M-%S')}"

    passphrase_desc, secret_env = resolve_passphrase(args)

    env = os.environ.copy()
    env["BORG_REPO"] = repo
    env.setdefault("LC_ALL", "C.UTF-8")
    env.update(secret_env)
    if args.rsh:
        env["BORG_RSH"] = args.rsh
    if not args.keep_env:
        env.setdefault("BORG_LOCK_WAIT", str(args.lock_wait))
        if major < 2:
            env.setdefault("BORG_EXIT_CODES", "modern")

    log_file = args.log_file or f"/var/log/borgbackup/{prefix}.log"
    if not args.log:
        log_file = None
    elif log_file:
        directory = os.path.dirname(log_file)
        try:
            if directory:
                os.makedirs(directory, exist_ok=True)
            with open(log_file, "a", encoding="utf-8") as handle:
                handle.write(f"\n{'=' * 78}\n"
                             f"{time.strftime('%F %T')} borg_backup.py "
                             f"{archive}\nrepository: {repo}\n")
        except OSError as exc:
            print(colorize(f"Warning: cannot use log file {log_file}: {exc}",
                           Colors.WARNING), file=sys.stderr)
            log_file = None

    runner = Runner(env, log_file, args.quiet)

    print()
    print(colorize("BORG BACKUP", Colors.HEADER + Colors.BOLD))
    rows = []
    if args.dry_run:
        rows.append(["mode", colorize("DRY RUN — nothing is written",
                                      Colors.WARNING + Colors.BOLD)])
    rows += [
        ["borg", f"{version} ({BORG_BIN})"],
        ["repository", repo],
        ["archive", archive],
        ["sources", ", ".join(args.sources)],
        ["compression", args.compression],
        ["prune", prune_summary(args, borg, prefix, retention, defaulted)],
        ["compact", "disabled" if (args.no_compact or args.dry_run)
         else f"yes (--threshold {args.compact_threshold})"],
        ["verify", "yes (borg check)" if args.verify else "no"],
        ["init", f"yes, if the repository is missing "
                 f"({borg.init_mode(args)})" if args.init
         else "no — borg will not create a missing repository"],
        ["lock", f"yes, waiting up to {args.lock_wait}s" if args.lock else "no"],
        ["log file", log_file or "none"],
    ]
    print_table(["", "SETTING"], rows, max_widths=[14, 100])

    lock = acquire_lock(repo, args.lock_wait, args.lock)
    if lock == "timeout":
        runner.close()
        fail(f"repository {repo} is busy (lock not acquired in "
             f"{args.lock_wait}s)", code=4)

    interrupted = False
    try:
        create = runner.run("create", borg.create(args, archive, args.sources))
        if args.init and create["rc"] in (13, 15):
            # borg initializes a repository by itself only when its path does
            # not exist at all; an existing (empty) directory is refused, so
            # initialize it here and retry. The failed attempt stays in the
            # phase table but must not decide the verdict.
            create["recoverable"] = True
            runner.run("init", borg.init(args))
            create = runner.run("create",
                                borg.create(args, archive, args.sources))
        if rc_class(create["rc"]) in ("ok", "warn"):
            if not args.no_prune:
                runner.run("prune", borg.prune(args, prefix, retention))
            if not args.no_compact and not args.dry_run:
                runner.run("compact", borg.compact(args))
            if args.verify and not args.dry_run:
                runner.run("verify", borg.check(args, archive))
            if args.show_archives and not args.dry_run:
                runner.run("archives",
                           borg.list_archives(args.show_archives))
    except KeyboardInterrupt:
        interrupted = True
        log_line("Interrupted — borg was terminated.", stream=sys.stderr)
    finally:
        if lock not in (None, "timeout"):
            fcntl.flock(lock, fcntl.LOCK_UN)
            lock.close()

    try:
        code = report(runner, args, borg, archive, repo, interrupted)
    finally:
        if log_file:
            runner.write_log(f"\noverall exit status: {code}\n")
            print(f"Log: {log_file}")
        runner.close()
    return code


def prune_summary(args, borg, prefix, retention, defaulted):
    if args.no_prune:
        return "disabled (--no-prune)"
    spec = ", ".join(f"--{option} {value}"
                     for option, value in retention.items())
    note = " [OMV defaults]" if defaulted else ""
    return f"{spec}{note} on {borg.archives_filter} " \
           f"{borg.archive_glob(f'{prefix}-*')}"


RANK = {"ok": 0, "warn": 1, "err": 2, "sig": 3}


def report(runner, args, borg, archive, repo, interrupted):
    """Print the report and return the exit status for the whole run."""
    if not runner.phases:
        print(colorize("Nothing ran.", Colors.WARNING))
        return 2

    creates = [phase for phase in runner.phases if phase["name"] == "create"]
    create = creates[-1] if creates else runner.phases[0]
    stats = create["stats"]
    overall = "sig" if interrupted else max(
        (p["class"] for p in runner.phases if not p.get("recoverable")),
        key=lambda cls: RANK[cls])
    total_elapsed = sum(p["elapsed"] for p in runner.phases)

    print()
    print(colorize("PHASES", Colors.HEADER + Colors.BOLD))
    rows = []
    for phase in runner.phases:
        label = rc_label(phase["rc"])
        if phase.get("recoverable"):
            label += " → retried"
        rows.append([
            phase["name"],
            colorize(label, STATUS_COLOR[phase["class"]]),
            f"{phase['counters']['added']} added / "
            f"{phase['counters']['changed']} changed"
            if phase["name"] == "create" and (args.list_files or
                                              phase["counters"]["added"]) else "",
            human_duration(phase["elapsed"]),
        ])
    rows.append([colorize("total", Colors.BOLD), "", "",
                 colorize(human_duration(total_elapsed), Colors.BOLD)])
    headers = ["PHASE", "RESULT", "ITEMS", "DURATION"]
    if not any(row[2] for row in rows[:-1]):
        headers[2] = ""
    print_table(headers, rows)

    print()
    print(colorize("ARCHIVE", Colors.HEADER + Colors.BOLD))
    new_bytes = stats.dedup_bytes()
    # borg's own duration excludes the repository handshake and cache
    # synchronisation, so the throughput figure describes the actual transfer
    create_secs = stats.duration or create["elapsed"]
    rate = (new_bytes / create_secs) if (new_bytes and create_secs > 0) else None

    if not stats.complete:
        rows = [["statistics", "none reported by borg"
                 + (" (dry runs report no sizes)" if args.dry_run else "")],
                ["wall time", human_duration(create_secs)]]
    else:
        rows = [
            ["repository", stats.repository or repo],
            ["archive", stats.archive or archive],
            ["fingerprint", stats.fingerprint or "-"],
            ["started", stats.start or "-"],
            ["finished", stats.end or "-"],
            ["duration", stats.duration_text or human_duration(create_secs)],
            ["files", stats.files or "-"],
            ["this archive", stats.sizes_summary()],
            ["new data", human_bytes(new_bytes) if new_bytes else "-"],
            ["throughput", f"{human_bytes(rate)}/s" if rate else "-"],
        ]
        if stats.all_archives:
            rows.append(["all archives", "  ".join(
                f"{name} {value}" for name, value in
                zip(("original", "compressed", "deduplicated"),
                    stats.all_archives))])
        if stats.chunk_index:
            rows.append(["chunks", f"{stats.chunk_index[0]} unique / "
                                   f"{stats.chunk_index[1]} total"])
        if args.dry_run:
            rows.insert(0, ["mode", "dry run — no archive was written"])
    print_table(["", "VALUE"], rows, max_widths=[14, 100])

    messages = []
    for phase in runner.phases:
        for level, text in phase_messages(phase):
            messages.append((phase["name"], level, text))

    if messages:
        print()
        print(colorize(f"MESSAGES ({len(messages)})", Colors.WARNING + Colors.BOLD))
        for phase, level, text in messages[:25]:
            color = {"ERROR": Colors.FAIL, "warning": Colors.WARNING,
                     "output": Colors.DIM}[level]
            print(f"  {colorize(f'{level:<7}', color)} [{phase}] {fit(text, 112)}")
        if len(messages) > 25:
            print(colorize(f"  … {len(messages) - 25} more in the log file",
                           Colors.DIM))

    print()
    verdict, color, summary = verdict_for(overall, runner, interrupted, stats,
                                          new_bytes, rate, create_secs, archive)
    print(colorize(verdict, color + Colors.BOLD),
          colorize(summary, Colors.DIM))
    print()
    return {"ok": 0, "warn": 1}.get(overall, 2)


def phase_messages(phase):
    """
    The human-useful lines of one phase.

    Errors and warnings are always shown. A phase that did not exit 0 also
    contributes its leftover output (already filtered by BORING in Stats.feed),
    because borg writes the actual reason as a bare line — "passphrase supplied
    in BORG_PASSPHRASE … is incorrect", for instance.
    """
    stats = phase["stats"]
    out = [("ERROR", text) for text in stats.errors]
    out += [("warning", text) for text in stats.warnings]
    if phase["rc"] != 0:
        out += [("output", text) for text in stats.plain[-6:]]
    return out


def verdict_for(overall, runner, interrupted, stats, new_bytes, rate,
                create_secs, archive):
    if interrupted:
        return ("FAILED", Colors.FAIL,
                "interrupted by the user (borg was terminated)")

    failed = [p for p in runner.phases if p["class"] in ("err", "sig")
              and not p.get("recoverable")]
    if failed:
        detail = ", ".join(f"{p['name']}={rc_label(p['rc'])}" for p in failed)
        # borg writes its own reason last, after any chatter
        lines = [text for level, text in phase_messages(failed[0])
                 if level in ("ERROR", "output")]
        hint = f" — {lines[-1]}" if lines else ""
        if any(p["rc"] in (13, 15) for p in failed):
            hint += "  (create it first: --init)"
        return ("FAILED", Colors.FAIL, f"{detail}{hint}")

    counts = stats.files
    volume = f", {human_bytes(new_bytes)} new" if new_bytes else ""
    speed = f", {human_bytes(rate)}/s" if rate else ""
    what = f"{counts} files" if counts else "no statistics"
    timing = human_duration(create_secs)
    warn = [p["name"] for p in runner.phases if p["class"] == "warn"]
    if warn:
        return ("SUCCESS (WITH WARNINGS)", Colors.WARNING,
                f"{what} → {archive} in {timing}{volume} — "
                f"warnings in: {', '.join(warn)}")
    return ("SUCCESS", Colors.OKGREEN, f"{what} → {archive} in {timing}{volume}{speed}")


if __name__ == "__main__":
    raise SystemExit(main())
